language: node_js
node_js:
- '6.1'
before_install:
- openssl aes-256-cbc -K $encrypted_ebc3a9840b87_key -iv $encrypted_ebc3a9840b87_iv
  -in deploy-key-digitalocean-travis.enc -out deploy-key-digitalocean-travis -d
